import HiddenCircuits.Circuit.Runtime.LetterEmitter
import HiddenCircuits.TrackTransport

/-! Fixed local physical words at a runtime unary base offset. Every literal
index is generated by real pushes and restored after its letter is emitted. -/
namespace HiddenCircuits.Circuit.Runtime.LetterEmitter
open HiddenCircuits.Complexity OracleBlock

noncomputable def drops : ℕ → OracleBlock 3
  | 0 => skip
  | k+1 => seq (GraphVerifier.Runtime.popDrop 0) (drops k)

theorem drops_executes (g : BitString → ℕ) (p k : ℕ) (stream : BitString) :
    (drops k).Executes g (store (p+k) stream [] []) (store p stream [] []) (3*k+1) := by
  induction k with
  | zero => simpa [drops] using skip_executes g (store p stream [] [])
  | succ k ih =>
    have hp : (GraphVerifier.Runtime.popDrop (0:Fin 4)).Executes g
        (store (p+(k+1)) stream [] []) (store (p+k) stream [] []) 1 := by
      convert GraphVerifier.Runtime.popDrop_executes (0:Fin 4) g (store (p+(k+1)) stream [] []) using 1
      funext i;fin_cases i <;> simp [store,show p+(k+1)=p+k+1 by omega,List.replicate_succ]
    convert seq_executes _ _ g hp ih using 1 <;> omega

noncomputable def offsetAtom (kind : LetterKind) (offset : ℕ) : OracleBlock 3 :=
  seq (prepend 0 (List.replicate offset true)) (seq (atom kind) (drops offset))

theorem offsetAtom_executes (g : BitString → ℕ) (kind : LetterKind) (p offset : ℕ) (stream : BitString) :
    (offsetAtom kind offset).Executes g (store p stream [] [])
      (store p ((chunk kind (p+offset)).reverse++stream) [] []) (14*p+20*offset+50) := by
  have hp : (prepend (0:Fin 4) (List.replicate offset true)).Executes g
      (store p stream [] []) (store (p+offset) stream [] []) (3*offset+1) := by
    convert prepend_executes g (0:Fin 4) (List.replicate offset true) (store p stream [] []) using 1
    · funext i;fin_cases i <;> simp [store,←List.replicate_add,Nat.add_comm]
    · simp
  have ha := atom_executes g kind (p+offset) stream
  have hd := drops_executes g p offset ((chunk kind (p+offset)).reverse++stream)
  convert seq_executes _ _ g hp (seq_executes _ _ g ha hd) using 1 <;> omega

lemma drops_queryFree (k : ℕ) : (drops k).QueryFree := by
  induction k with
  | zero => exact skip_queryFree
  | succ k ih => exact seq_queryFree _ _ (GraphVerifier.Runtime.popDrop_queryFree _) ih
lemma offsetAtom_queryFree (kind : LetterKind) (offset : ℕ) : (offsetAtom kind offset).QueryFree :=
  seq_queryFree _ _ (prepend_queryFree _ _) (seq_queryFree _ _ (atom_queryFree _) (drops_queryFree _))

noncomputable def fixedWord {n : ℕ} (w : List (Letter n)) : OracleBlock 3 :=
  sequence (w.map (fun l => offsetAtom l.kind l.index.val))

def wordBitsAt {n : ℕ} (p : ℕ) (w : List (Letter n)) : BitString :=
  w.flatMap (fun l => chunk l.kind (p+l.index.val))
def wordCost {n : ℕ} (p : ℕ) (w : List (Letter n)) : ℕ :=
  w.length*(14*p+52)+20*(w.map (fun l => l.index.val)).sum+1

lemma update_stream (p : ℕ) (stream counter temporary next : BitString) :
    Function.update (store p stream counter temporary) 1 next=store p next counter temporary := by
  funext i;fin_cases i <;> rfl

lemma wordCost_eq {n : ℕ} (p : ℕ) (w : List (Letter n)) :
    wordCost p w=(w.map (fun l => 14*p+20*l.index.val+50)).sum+2*w.length+1 := by
  induction w with
  | nil => simp [wordCost]
  | cons l w ih =>
    simp only [wordCost,List.length_cons,List.map_cons,List.sum_cons] at *
    nlinarith

/-- A fixed local word is compiled once; its runtime base offset is read from
port0 and restored, and all bytes are appended to reverse accumulator1. -/
theorem fixedWord_executes {n : ℕ} (g : BitString → ℕ) (w : List (Letter n)) (p : ℕ) (stream : BitString) :
    (fixedWord w).Executes g (store p stream [] [])
      (store p ((wordBitsAt p w).reverse++stream) [] []) (wordCost p w) := by
  have hitem (l : Letter n) (_ : l∈w) (out : BitString) :
      (offsetAtom l.kind l.index.val).Executes g (Function.update (store p [] [] []) 1 out)
        (Function.update (store p [] [] []) 1 ((chunk l.kind (p+l.index.val)).reverse++out)) (14*p+20*l.index.val+50) := by
    simpa only [update_stream] using offsetAtom_executes g l.kind p l.index.val out
  simpa only [update_stream,wordCost_eq] using sequence_emit g w (fun l => offsetAtom l.kind l.index.val)
    (fun l => chunk l.kind (p+l.index.val)) (fun l => 14*p+20*l.index.val+50) (store p [] [] []) 1 hitem stream

lemma wordCost_bound {n : ℕ} (p : ℕ) (w : List (Letter n)) :
    wordCost p w≤w.length*(14*p+20*n+52)+1 := by
  have hsum : (w.map (fun l => l.index.val)).sum≤w.length*n := by
    induction w with
    | nil => simp
    | cons l w ih =>
      have h := l.index.isLt
      have hn : l.index.val≤n := by omega
      simp only [List.map_cons,List.sum_cons,List.length_cons]
      nlinarith
  dsimp [wordCost]
  nlinarith

lemma fixedWord_queryFree {n : ℕ} (w : List (Letter n)) : (fixedWord w).QueryFree := by
  apply sequence_queryFree
  intro B hb
  obtain ⟨l,hl,rfl⟩ := List.mem_map.mp hb
  exact offsetAtom_queryFree _ _

noncomputable def fixedWordOn {n k : ℕ} (φ : Fin 4 ↪ Fin (k+1)) (w : List (Letter n)) : OracleBlock k := rename (fixedWord w) φ

theorem fixedWordOn_executes {n k : ℕ} (φ : Fin 4 ↪ Fin (k+1)) (g : BitString → ℕ)
    (s : Store k) (w : List (Letter n)) (p : ℕ) (hs : s ∘ φ=store p (s (φ 1)) [] []) :
    (fixedWordOn φ w).Executes g s (Function.update s (φ 1) ((wordBitsAt p w).reverse++s (φ 1))) (wordCost p w) := by
  apply rename_executes_to _ φ g (fixedWord_executes g w p (s (φ 1))) hs
  · have he : (Function.update s (φ 1) ((wordBitsAt p w).reverse++s (φ 1))) ∘ φ=
        Function.update (s ∘ φ) 1 ((wordBitsAt p w).reverse++s (φ 1)) := by
      funext i;simp [Function.comp_def,Function.update_apply,φ.injective.eq_iff]
    rw [he,hs,update_stream]
  · intro i hi;exact Function.update_of_ne (hi 1).symm _ _
lemma fixedWordOn_queryFree {n k : ℕ} (φ : Fin 4 ↪ Fin (k+1)) (w : List (Letter n)) :
    (fixedWordOn φ w).QueryFree := rename_queryFree _ _ (fixedWord_queryFree w)

lemma wordBitsAt_embed {n N : ℕ} (w : List (Letter n)) (p : ℕ) (hp : p+n≤N) :
    wordBitsAt p w=encodeBitList ((w.map (Letter.embed N p hp)).map letterBits) := by
  rw [←chunks_eq]
  simp only [wordBitsAt,List.flatMap_map,Function.comp_def,Letter.embed]

lemma wordBitsAt_zero {n : ℕ} (w : List (Letter n)) : wordBitsAt 0 w=encodeBitList (w.map letterBits) := by
  simpa only [wordBitsAt,Nat.zero_add] using chunks_eq w

end HiddenCircuits.Circuit.Runtime.LetterEmitter
