import HiddenCircuits.Circuit.Runtime.SpectralCommonDenominator
import HiddenCircuits.Circuit.Runtime.SpectralScalesFrame
import HiddenCircuits.Circuit.Runtime.SpectralTargets
import HiddenCircuits.Circuit.Runtime.SpectralFoldLoop
import HiddenCircuits.Circuit.Runtime.SpectralZeroVector

/-! Actual degree-only preparation of basis rows, common denominator, and row
scales. Every value is generated by the finite instruction graph. -/
namespace HiddenCircuits.Circuit.Runtime.SpectralWeightsProgram
open HiddenCircuits.Complexity HiddenCircuits.Complexity.OracleBlock
open HiddenCircuits.Complexity.BinaryArithmetic Polynomial
open SpectralWeights

def state (g : ℕ) (mode : Bool) (count ds rows den scalar aux outD outN : BitString) : Store 35 := fun i =>
  if i.val=0 then List.replicate g true else if i.val=2 then count else if i.val=3 then ds
  else if i.val=4 then rows else if i.val=5 then den else if i.val=6 then scalar else if i.val=7 then aux
  else if i.val=33 then [mode] else if i.val=34 then outD else if i.val=35 then outN else []
 def countWord (g : ℕ) : BitString := List.replicate (SpectralTable.nodeCount g) true
 def denominatorStream (g : ℕ) : BitString := encodeBitList (SpectralTable.denominators g)
 def tableStream (g : ℕ) : BitString := encodeBitList (SpectralTable.vectors g)
 def targetStream (g : ℕ) (mode : Bool) : BitString := encodeBitList ((SpectralTargets.weights g mode).map signedBits)
 def scaleStream (g : ℕ) (mode : Bool) : BitString :=
  encodeBitList ((spectralIndices g).map (fun i => signedBits (scale g (SpectralTargets.base mode) i)))
 def numeratorStream (g : ℕ) (mode : Bool) : BitString :=
  encodeBitList ((vector g (SpectralTargets.base mode) (spectralIndices g)).map signedBits)

def tableEmbedding : Fin 33 ↪ Fin 36 where
  toFun i := ⟨i.val,by omega⟩
  inj' := by intro i j h;exact Fin.ext (congrArg (fun z : Fin 36 => z.val) h)
 def targetsEmbedding : Fin 9 ↪ Fin 36 where
  toFun i := if i.val=0 then 0 else if i.val=1 then 33 else if i.val=2 then 7 else ⟨i.val+5,by omega⟩
  inj' := by intro i j h;fin_cases i <;> fin_cases j <;> simp_all
 def denominatorEmbedding : Fin 7 ↪ Fin 36 where
  toFun i := if i.val=0 then 5 else ⟨i.val+7,by omega⟩
  inj' := by intro i j h;fin_cases i <;> fin_cases j <;> simp_all
 def scalesEmbedding : Fin 21 ↪ Fin 36 where
  toFun i := if i.val=0 then 6 else if i.val=1 then 3 else if i.val=2 then 7 else ⟨i.val+5,by omega⟩
  inj' := by intro i j h;fin_cases i <;> fin_cases j <;> simp_all

noncomputable def table : OracleBlock 35 := SpectralTable.programOn tableEmbedding
noncomputable def targets : OracleBlock 35 := SpectralTargets.programOn targetsEmbedding
noncomputable def commonDenominator : OracleBlock 35 := SpectralCommonDenominator.programOn denominatorEmbedding
noncomputable def scales : OracleBlock 35 := SpectralScales.programOn scalesEmbedding
noncomputable def prepareDenominator : OracleBlock 35 := seq (copyOn 3 5 8 (by decide) (by decide) (by decide)) commonDenominator
noncomputable def prepareScales : OracleBlock 35 := seq (copyOn 5 6 8 (by decide) (by decide) (by decide)) scales
noncomputable def prepare : OracleBlock 35 := seq table (seq targets (seq prepareDenominator prepareScales))
noncomputable def scalesInputBound : Polynomial ℕ := SpectralFold.scalarBound+SpectralTable.vectorBound+6*(X+1)^2
noncomputable def scalesTime : Polynomial ℕ := SpectralScales.time.comp scalesInputBound
noncomputable def prepareTime : Polynomial ℕ := SpectralTable.time+SpectralTargets.time+
  SpectralCommonDenominator.spectralTime+scalesTime+5*SpectralTable.vectorBound+5*SpectralFold.scalarBound+20

 theorem base_abs (mode : Bool) : (SpectralTargets.base mode).natAbs≤1 := by cases mode <;> decide

 theorem table_executes (oracle : BitString → ℕ) (g : ℕ) (mode : Bool) :
    ∃ t, table.Executes oracle (state g mode [] [] [] [] [] [] [] [])
      (state g mode (countWord g) (denominatorStream g) (tableStream g) [] [] [] [] []) t ∧ t≤SpectralTable.time.eval g := by
  obtain ⟨t,ht,hb⟩ := SpectralTable.programOn_executes tableEmbedding oracle (state g mode [] [] [] [] [] [] [] []) g
    (by funext i;fin_cases i <;> rfl)
  refine ⟨t,?_,hb⟩
  convert ht using 1
  funext i;fin_cases i <;> simp [state,tableEmbedding,countWord,denominatorStream,tableStream]

 theorem targets_executes (oracle : BitString → ℕ) (g : ℕ) (mode : Bool) :
    ∃ t, targets.Executes oracle (state g mode (countWord g) (denominatorStream g) (tableStream g) [] [] [] [] [])
      (state g mode (countWord g) (denominatorStream g) (tableStream g) [] [] (targetStream g mode) [] []) t ∧
      t≤SpectralTargets.time.eval g := by
  obtain ⟨t,ht,hb⟩ := SpectralTargets.programOn_executes targetsEmbedding oracle
    (state g mode (countWord g) (denominatorStream g) (tableStream g) [] [] [] [] []) g mode
    (by funext i;fin_cases i <;> rfl)
  refine ⟨t,?_,hb⟩
  convert ht using 1
  funext i;fin_cases i <;> simp [state,targetsEmbedding,targetStream]

 theorem commonDenominator_executes (oracle : BitString → ℕ) (g : ℕ) (mode : Bool) :
    ∃ t, commonDenominator.Executes oracle
      (state g mode (countWord g) (denominatorStream g) (tableStream g) (denominatorStream g) [] (targetStream g mode) [] [])
      (state g mode (countWord g) (denominatorStream g) (tableStream g) (signedBits (denominator g)) [] (targetStream g mode) [] []) t ∧
      t≤SpectralCommonDenominator.spectralTime.eval g := by
  obtain ⟨t,ht,hb⟩ := SpectralCommonDenominator.program_spectral_executes oracle g
  refine ⟨t,?_,hb⟩
  apply rename_executes_to SpectralCommonDenominator.program denominatorEmbedding oracle ht
  · funext i;fin_cases i <;> rfl
  · funext i;fin_cases i <;> rfl
  · intro i hi;fin_cases i <;> first | rfl | exact False.elim (hi 0 rfl)

 theorem denominator_length (g : ℕ) : (signedBits (denominator g)).length≤SpectralFold.scalarBound.eval g := by
  have h := signedBits_length_of_abs_bound (denominator_envelope g)
  simpa only [SpectralFold.scalarBound,SpectralTable.entryBound,SpectralWeights.denominatorExponent,spectralBasisBitBound,
    eval_add,eval_mul,eval_pow,eval_X,eval_one,eval_ofNat] using h

 theorem scales_executes (oracle : BitString → ℕ) (g : ℕ) (mode : Bool) :
    ∃ t, scales.Executes oracle
      (state g mode (countWord g) (denominatorStream g) (tableStream g) (signedBits (denominator g))
        (signedBits (denominator g)) (targetStream g mode) [] [])
      (state g mode (countWord g) [] (tableStream g) (signedBits (denominator g)) (scaleStream g mode) [] [] []) t ∧
      t≤scalesTime.eval g := by
  let ps := (spectralIndices g).map (fun i => (spectralBasisDenominator g i,target g (SpectralTargets.base mode) i))
  have hv : ∀p∈ps,p.1≠0 ∧ p.1∣denominator g := by
    intro p hp
    obtain ⟨i,hi,rfl⟩ := List.mem_map.mp hp
    exact ⟨spectralBasisDenominator_ne_zero g i,denominator_divisible g i⟩
  obtain ⟨t,ht,hb⟩ := SpectralScales.program_executes oracle (denominator g) ps hv
  have hx : ps.map (fun p => signedBits p.1)=SpectralTable.denominators g := by
    simp [ps,List.map_map,SpectralTable.denominators,Function.comp_def]
  have hy : ps.map (fun p => signedBits p.2)=(SpectralTargets.weights g mode).map signedBits := by
    simp [ps,List.map_map,SpectralTargets.weights,target,Function.comp_def]
  have ho : (SpectralScales.output (denominator g) ps).map signedBits=
      (spectralIndices g).map (fun i => signedBits (scale g (SpectralTargets.base mode) i)) := by
    simp [SpectralScales.output,SpectralScales.value,ps,List.map_map,scale,Function.comp_def]
  rw [hx,hy,ho] at ht
  refine ⟨t,?_,hb.trans ?_⟩
  · apply rename_executes_to SpectralScales.program scalesEmbedding oracle ht
    · funext i;fin_cases i <;> rfl
    · funext i;fin_cases i <;> rfl
    · intro i hi;fin_cases i <;> first | rfl | exact False.elim (hi 0 rfl) | exact False.elim (hi 1 rfl) | exact False.elim (hi 2 rfl)
  · simp only [scalesTime,eval_comp]
    apply polynomial_nat_eval_mono SpectralScales.time
    have hd := denominator_length g
    have hx' := SpectralTable.denominators_length g
    have hy' := SpectralTargets.weight_stream_length g mode
    simp only [SpectralScales.inputLength,hx,hy,scalesTime,scalesInputBound,eval_comp,eval_add,eval_mul,eval_pow,eval_X,eval_one,eval_ofNat]
    omega

 theorem prepare_executes (oracle : BitString → ℕ) (g : ℕ) (mode : Bool) :
    ∃ t, prepare.Executes oracle (state g mode [] [] [] [] [] [] [] [])
      (state g mode (countWord g) [] (tableStream g) (signedBits (denominator g)) (scaleStream g mode) [] [] []) t ∧
      t≤prepareTime.eval g := by
  obtain ⟨a,ha,hab⟩ := table_executes oracle g mode
  obtain ⟨b,hb,hbb⟩ := targets_executes oracle g mode
  let s₁ := state g mode (countWord g) (denominatorStream g) (tableStream g) [] [] (targetStream g mode) [] []
  let s₂ := state g mode (countWord g) (denominatorStream g) (tableStream g) (denominatorStream g) [] (targetStream g mode) [] []
  let s₃ := state g mode (countWord g) (denominatorStream g) (tableStream g) (signedBits (denominator g)) [] (targetStream g mode) [] []
  let s₄ := state g mode (countWord g) (denominatorStream g) (tableStream g) (signedBits (denominator g))
    (signedBits (denominator g)) (targetStream g mode) [] []
  have h₁ : (copyOn (3:Fin 36) 5 8 (by decide) (by decide) (by decide)).Executes oracle s₁ s₂ (5*(denominatorStream g).length+2) := by
    convert copyOn_executes oracle (3:Fin 36) 5 8 (by decide) (by decide) (by decide) s₁ rfl using 1
    funext i;fin_cases i <;> simp [s₁,s₂,state]
  obtain ⟨c,hc,hcb⟩ := commonDenominator_executes oracle g mode
  have h₂ : (copyOn (5:Fin 36) 6 8 (by decide) (by decide) (by decide)).Executes oracle s₃ s₄ (5*(signedBits (denominator g)).length+2) := by
    convert copyOn_executes oracle (5:Fin 36) 6 8 (by decide) (by decide) (by decide) s₃ rfl using 1
    funext i;fin_cases i <;> simp [s₃,s₄,state]
  obtain ⟨d,hd,hdb⟩ := scales_executes oracle g mode
  refine ⟨a+(b+(((5*(denominatorStream g).length+2)+c+2)+((5*(signedBits (denominator g)).length+2)+d+2)+2)+2)+2,
    seq_executes _ _ oracle ha (seq_executes _ _ oracle hb
      (seq_executes _ _ oracle (seq_executes _ _ oracle h₁ hc) (seq_executes _ _ oracle h₂ hd))),?_⟩
  have hden := SpectralTable.denominators_length g
  have hD := denominator_length g
  simp only [prepareTime,eval_add,eval_mul,eval_ofNat]
  change (denominatorStream g).length≤SpectralTable.vectorBound.eval g at hden
  omega

 theorem prepare_queryFree : prepare.QueryFree := seq_queryFree _ _ (SpectralTable.programOn_queryFree _)
  (seq_queryFree _ _ (SpectralTargets.programOn_queryFree _)
    (seq_queryFree _ _ (seq_queryFree _ _ (copyOn_queryFree _ _ _ _ _ _) (SpectralCommonDenominator.programOn_queryFree _))
      (seq_queryFree _ _ (copyOn_queryFree _ _ _ _ _ _) (SpectralScales.programOn_queryFree _))))
end HiddenCircuits.Circuit.Runtime.SpectralWeightsProgram
